import React, { useEffect, useState } from 'react';
import './Round3.css';

const Round3 = () => {
  const [panels, setPanels] = useState([]); const [loading, setLoading] = useState(true); const [selectedPanel, setSelectedPanel] = useState('1');
  useEffect(() => { const fetchPanels = async () => { try { const response = await fetch('/api/panels'); if (response.ok) setPanels(await response.json()); } catch (error) { console.error('Error fetching panels:', error); } finally { setLoading(false); } }; fetchPanels(); const interval = setInterval(fetchPanels, 5000); return () => clearInterval(interval); }, []);
  return <main className="round3-container"><header className="round3-header"><div><p className="eyebrow">BMSIT&amp;M · INTERNAL HACKATHON</p><h1 className="round3-title">Round 3<br /><span>Team queue</span></h1></div></header><div className="mobile-panel-picker"><label htmlFor="panel-select">VIEW PANEL</label><select id="panel-select" value={selectedPanel} onChange={(event) => setSelectedPanel(event.target.value)}>{panels.map((panel) => <option value={String(panel.panelNumber)} key={panel.panelNumber}>Panel {String(panel.panelNumber).padStart(2, '0')}</option>)}</select></div>{loading && !panels.length ? <div className="loading-state">Loading team queues...</div> : <div className="panels-grid">{panels.map((panel) => { const teams = panel.teamsList || []; const current = panel.currentTeamIndex ?? 0; return <section className={`panel-card panel-${panel.panelNumber}`} key={panel._id || panel.panelNumber}><div className="panel-card-head"><span className="panel-kicker">PANEL</span><h2>{String(panel.panelNumber).padStart(2, '0')}</h2><span className="queue-count">{teams.length} TEAMS</span></div><div className="team-list">{teams.map((team, index) => <div className={`team-row ${index === current ? 'is-current' : ''}`} key={`${team}-${index}`}><span className="team-number">{String(index + 1).padStart(2, '0')}</span><span className="team-name">{team}</span>{index === current && <span className="presenting-pill">ON STAGE</span>}</div>)}</div><p className="last-updated">Updated {new Date(panel.lastUpdated).toLocaleTimeString()}</p></section>; })}</div>}</main>;
};
export default Round3;
